### ISSUE TITLE
steam integration question

### ISSUE THREAD

**Issue by uzoc** [muttleyxd/arma3-unix-launcher#2]
I know it's still on the ToDo list, but does your launcher detect the steam install directory? The launcher keeps requesting arma3.i386 when pointed to the steam install directory.

**Comment by muttleyxd** [comment]
What platform are you on? Also where do you have Steam installed and where did you install ArmA?

It detects Steam's install dir and then read it's config file (config.vdf), where it gets information about possible install locations. After that these locations are scanned for existing ArmA 3 installation.

**Comment by uzoc** [comment]
I'm on a CustoMac using Serria 10.12.3 - I'm hoping it's not a hackintosh problem, but it very well could be. DOTA 2 is working fine, wanted to test something a little heavier. 

It's installed to Application Support under my user Library, I'm pointing your launcher to the steamapps>common>arma3 folder.

Thanks for responding so quickly.

**Comment by muttleyxd** [comment]
I've tested this on Hackintosh too (would never buy a Mac :P) and it worked fine. Did you launch the game before using the launcher?

/Steam/config/config.vdf
Would you mind sharing that file? I'm interested in lines which contain "BaseInstallFolder_" - it tells about locations where your Steam games are installed.

**Comment by uzoc** [comment]
Another issue I'm having is ArmA3 is launching into a black screen with audio. Trying to fix that before going further with the launcher. I did try to manually point it to the install folder. 

I don't have BaseInstallFolder_ entry in that file. I searched through it with the search function and with my eyes haha.

There is a subheading "Directories" under "LocalLibrary" but it looks to be encoded. That file also has some personal information in it! Lol.

**Comment by muttleyxd** [comment]
I guess I'll have to reinstall my Mac and try to test it again. I don't have an idea what could cause it. Problem is that I'm having my university exams until 16th of February, so I won't have much time to do work on the launcher.

Also could you send me a list of files in ArmA's directory? And which one is executable? I could try making a patch which could fix that

**Comment by uzoc** [comment]
The executable that I'm pointing it towards was ArmA3.app stored in the Steam/steamapps/common/ Arma 3 folder. Am I doing this wrong? And no worries about the exams. I'm sure I can figure this out. Part of the fun.

**Comment by muttleyxd** [comment]
It seems like my launcher is looking for a wrong file, it's arma3.i386 on Linux, don't know how it passed through my testing, I've launched it few times before.

I've pushed q&d fix for that. I'd be grateful if you can test it.

**Comment by uzoc** [comment]
I will test it. I'm still having issues with ArmA3 giving me a black screen after launching. But I should be able to test the launcher (which I had hoped would give me some access to resolution settings so I could change how it launches.)

**Comment by uzoc** [comment]
I used the install script. It does seem to detect the install now, but not automatically, I had to point to the .app.

**Comment by uzoc** [comment]
The launcher does work for changing the start up parameters, nice. Will do more testing with mods later. Is it possible to have an option to select which video device to use?

**Comment by uzoc** [comment]
By the way, besides the dependencies, is the app itself and the folder all that is put onto the computer? How would I uninstall for example?

**Comment by muttleyxd** [comment]
Sorry for late response. Just had an exam.
No option for video device for now - can you set it manually through config file or game parameter? I don't have any device with multiple video cards, so can't test it at all. If you can do that through interacting with ArmA's game files I guess I could work out something.

Uninstalling - just remove Homebrew, I think it'll delete all the packages it downloaded. It's not much though. Probably 30 to 50 MB. If removing Homebrew doesn't delete these packages, then you need to do this:

brew uninstall cmake
brew uninstall gtkmm3

From there you can uninstall Homebrew.

I'm not providing an uninstall script for one reason - deleting these packages could break something if something else depends on them.

**Comment by muttleyxd** [comment]
Semi-fix posted - you still need to give ArmA's install directory when the launcher asks, but the mod detection should work now.

**Comment by muttleyxd** [comment]
Fixed quite some time ago. Forgot to close
