### ISSUE TITLE
[critical] Direct launch failed, exception: Syntax error: VDF: Quote or bracket expected

### ISSUE THREAD

**Issue by jurosic** [muttleyxd/arma3-unix-launcher#208]
Nothing more to add.
Here's verbose: 

```[2022-03-07 16:57:20.432] [trace] void MainWindow::on_button_start_clicked():124
[2022-03-07 16:57:20.502] [trace] Mod list: 
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/450814997
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/463939057
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/861133494
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1779063631
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/333310405
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2268351256
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1180533757
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/945476727
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1510335080
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/751965892
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1911374016
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2018593688
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2231150238
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2412203827
[2022-03-07 16:57:20.502] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1841367366
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2035305606
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1180534892
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1486541773
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2353214593
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2041057379
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2140308792
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1848649183
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/825179978
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/825181638
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2461607508
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2129532219
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1703187116
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1745501106
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1858070328
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/787892271
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1314910827
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1745501605
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2131302796
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/753946944
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/820924072
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/623475643
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1623498241
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2034363662
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1770265310
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2551358217
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2626999580
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/950889473
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/2020940806
[2022-03-07 16:57:20.503] [trace] path: /run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/workshop/content/107410/1321663083
[2022-03-07 16:57:20.570] [debug] Writing config to '/run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/common/Arma 3/../../compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/Arma3.cfg':
steamLanguage="";
language="English";
forcedAdapterId=-1;
detectedAdapterId=0;
detectedAdapterVendorId=4098;
detectedAdapterDeviceId=26591;
detectedAdapterSubSysId=0;
detectedAdapterRevision=0;
detectedAdapterBenchmark=60;
detectedCPUBenchmark=135;
detectedCPUFrequency=2496;
detectedCPUCores=4;
detectedCPUDescription="Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz";
displayMode=2;
winX=0;
winY=0;
winWidth=64;
winHeight=48;
winDefWidth=0;
winDefHeight=0;
fullScreenWidth=1920;
fullScreenHeight=1080;
refresh=60;
renderWidth=1920;
renderHeight=1080;
multiSampleCount=1;
multiSampleQuality=0;
particlesQuality=2;
GPU_MaxFramesAhead=0;
GPU_DetectedFramesAhead=0;
HDRPrecision=16;
vsync=0;
AToC=15;
cloudsQuality=2;
waterSSReflectionsQuality=1;
pipQuality=3;
dynamicLightsQuality=1;
PPAA=9;
ppSSAO=4;
ppCaustics=1;
tripleBuffering=0;
ppBloom=1;
ppRotBlur=1;
ppRadialBlur=1;
ppDOF=1;
ppSharpen=0.5;
class ModLauncherList
{
    class Mod1
    {
        dir="450814997";
        name="Community Base Addons v3.15.6";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\450814997";
    };
    class Mod2
    {
        dir="463939057";
        name="Advanced Combat Environment 0.0.0";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\463939057";
    };
    class Mod3
    {
        dir="861133494";
        name="JSRS Soundmod - CE.20.0423";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\861133494";
    };
    class Mod4
    {
        dir="1779063631";
        name="Zeus Enhanced 1.12.1";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1779063631";
    };
    class Mod5
    {
        dir="333310405";
        name="Enhanced Movement";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\333310405";
    };
    class Mod6
    {
        dir="2268351256";
        name="Tier One Weapons";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2268351256";
    };
    class Mod7
    {
        dir="1180533757";
        name="JSRS Soundmod - RHS USF Support CE.20.0419";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1180533757";
    };
    class Mod8
    {
        dir="945476727";
        name="JSRS Soundmod - RHS AFRF Support CE.20.0419";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\945476727";
    };
    class Mod9
    {
        dir="1510335080";
        name="SPS AI AXMC";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1510335080";
    };
    class Mod10
    {
        dir="751965892";
        name="Advanced Combat Radio Environment 2";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\751965892";
    };
    class Mod11
    {
        dir="1911374016";
        name="ACE Vehicle Medical";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1911374016";
    };
    class Mod12
    {
        dir="2018593688";
        name="Zeus Enhanced - ACE3 Compatibility";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2018593688";
    };
    class Mod13
    {
        dir="2231150238";
        name="Freestyles Crash Landing";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2231150238";
    };
    class Mod14
    {
        dir="2412203827";
        name="Escape From Tarkov Weapon Sounds - Tier One Weapons";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2412203827";
    };
    class Mod15
    {
        dir="1841367366";
        name="Escape From Tarkov Footsteps [JSRS Compatible ver.]";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1841367366";
    };
    class Mod16
    {
        dir="2035305606";
        name="Escape From Tarkov Weapon Sounds [RHS] (JSRS ver.)";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2035305606";
    };
    class Mod17
    {
        dir="1180534892";
        name="JSRS Soundmod - RHS GREF Support CE.20.0419";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1180534892";
    };
    class Mod18
    {
        dir="1486541773";
        name="JSRS Soundmod - RHS SAF Support CE.20.0419";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1486541773";
    };
    class Mod19
    {
        dir="2353214593";
        name="Tier One Weapons Optics NVG Compatibility";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2353214593";
    };
    class Mod20
    {
        dir="2041057379";
        name="A3 Thermal Improvement";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2041057379";
    };
    class Mod21
    {
        dir="2140308792";
        name="ACRE Animations";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2140308792";
    };
    class Mod22
    {
        dir="1848649183";
        name="JSRS SOUNDMOD - IFA3 Mod Sounds";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1848649183";
    };
    class Mod23
    {
        dir="825179978";
        name="Enhanced Soundscape";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\825179978";
    };
    class Mod24
    {
        dir="825181638";
        name="DynaSound 2";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\825181638";
    };
    class Mod25
    {
        dir="2461607508";
        name="Simple Suppress 1.1.0";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2461607508";
    };
    class Mod26
    {
        dir="2129532219";
        name="Project SFX: Remastered";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2129532219";
    };
    class Mod27
    {
        dir="1703187116";
        name="VET_Unflipping";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1703187116";
    };
    class Mod28
    {
        dir="1745501106";
        name="Hatchet Framework - Development Version";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1745501106";
    };
    class Mod29
    {
        dir="1858070328";
        name="LAMBS RPG";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1858070328";
    };
    class Mod30
    {
        dir="787892271";
        name="A-10 Warthog";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\787892271";
    };
    class Mod31
    {
        dir="1314910827";
        name="Breaching Charge";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1314910827";
    };
    class Mod32
    {
        dir="1745501605";
        name="H-60 pack - Development Version";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1745501605";
    };
    class Mod33
    {
        dir="2131302796";
        name="F/A-18 Super Hornet BETA pack";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2131302796";
    };
    class Mod34
    {
        dir="753946944";
        name="Immersion Cigs";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\753946944";
    };
    class Mod35
    {
        dir="820924072";
        name="BackpackOnChest";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\820924072";
    };
    class Mod36
    {
        dir="623475643";
        name="3den Enhanced";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\623475643";
    };
    class Mod37
    {
        dir="1623498241";
        name="Turret Enhanced";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1623498241";
    };
    class Mod38
    {
        dir="2034363662";
        name="Enhanced Movement Rework";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2034363662";
    };
    class Mod39
    {
        dir="1770265310";
        name="No More Aircraft Bouncing";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1770265310";
    };
    class Mod40
    {
        dir="2551358217";
        name="KAT - Pharmacy";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2551358217";
    };
    class Mod41
    {
        dir="2626999580";
        name="Snus";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2626999580";
    };
    class Mod42
    {
        dir="950889473";
        name="EnhancedTrenches";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\950889473";
    };
    class Mod43
    {
        dir="2020940806";
        name="KAT - Advanced Medical";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\2020940806";
    };
    class Mod44
    {
        dir="1321663083";
        name="ITC Air Systems";
        origin="GAME DIR";
        fullPath="Z:\run\media\jurosic_park\2ndSSD\SteamLibrary\steamapps\workshop\content\107410\1321663083";
    };
};

[2022-03-07 16:57:20.570] [trace] void ARMA3::Client::Start(const string&, const string&, bool, bool):192 arguments: ' -cpuCount=4 -enableHT -exThreads=7 -filePatching -hugepages -noLogs -noSplash -skipIntro -world=empty', user_environment_variables: '', launch_directly: true, disable_esync: false
[2022-03-07 16:57:20.570] [trace] void {anonymous}::direct_launch(const std::filesystem::__cxx11::path&, const std::filesystem::__cxx11::path&, const string&, bool, const string&, bool):63 arma path: '"/run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/common/Arma 3"', executable path: '"/run/media/jurosic_park/2ndSSD/SteamLibrary/steamapps/common/Arma 3/arma3_x64.exe"', arguments:  -cpuCount=4 -enableHT -exThreads=7 -filePatching -hugepages -noLogs -noSplash -skipIntro -world=empty, is_proton: true, user_environment_variables: , disable_esync: false
[2022-03-07 16:57:20.570] [info] Steam path: /home/jurosic_park/.local/share/Steam
[2022-03-07 16:57:20.570] [trace] GetCompatibilityToolForAppId:86
[2022-03-07 16:57:20.571] [critical] Direct launch failed, exception: Syntax error: VDF: Quote or bracket expected
```

EDIT: Code blocks dont work :(

**Comment by muttleyxd** [comment]
Code block didn't work because it needs 3 backticks, not two

\`\`\`
logs
\`\`\`

> [2022-03-07 16:57:20.571] [critical] Direct launch failed, exception: Syntax error: VDF: Quote or bracket expected

This error got fixed by #195. Which release of launcher are you running?

**Comment by jurosic** [comment]
i did a full system update right before i opened this issue and it didnt fix it, so probably the latest? im gonna go check around

**Comment by jurosic** [comment]
changed to arma3-unix-launcher-git and now all works fine, should i close the issue?

**Comment by muttleyxd** [comment]
I can close it myself, good to hear that it works 👍

**Comment by Sora012** [comment]
Using steam beta (Dec 10th 2022), this issue is occurring for me on Archlinux with compiling from source, and using arma3-unix-launcher-bin from AUR

**Comment by jurosic** [comment]
try using `arma3-unix-launcher-git`

**Comment by Sora012** [comment]
I've used both arm3-unix-launcher-bin, arma3-linux-launcher-git, and manually compiled from source from this repo. The issue remains.

**Comment by muttleyxd** [comment]
Reopening this, I'll try to investigate this when I have some free time

**Comment by muttleyxd** [comment]
@Sora012 I'll need verbose logs to continue with this issue - it doesn't want to reproduce for me. I tried both with Steam integration enabled and disabled, both seem to work fine.

You can get verbose logs by running
`arma3-unix-launcher --verbose`

**Comment by Sora012** [comment]
I'm gonna toss it up to Archlinux being broken. I'm on Fedora to test network issues I am having which are still occuring, but the launcher seems to work fine on steam beta in Fedora. So I really don't know what caused it to break for Arch, even with a fresh compile and install of the launcher.

As it stands I can't reproduce on Fedora, and Archlinux will not be in a working situation until atleast the 17th if the new network card arrives in time.

**Comment by muttleyxd** [comment]
@Sora012 Can you try the newest AppImage from here?

https://github.com/muttleyxd/arma3-unix-launcher/releases/tag/commit-370

**Comment by muttleyxd** [comment]
Closing as inactive. Feel free to reopen

**Comment by maxwelljens** [comment]
Having the same error with commit 383 release of the ArmA 3 launcher. Here are the logs:
[arma3_launcher_error.log](https://github.com/muttleyxd/arma3-unix-launcher/files/11489226/arma3_launcher_error.log)

**Comment by Langolyers** [comment]
Having the same issue on both AUR releases (bin and git) and building from source running Manjaro. Was working fine until last weekend, maybe something updated on Steam's end. 

Verbose logs in case it is useful:

```
[2023-08-27 10:38:47.840] [info] Started Arma 3 Unix Launcher, config file path: "/home/lango/.config/a3unixlauncher/launcher.conf"
[2023-08-27 10:38:47.841] [debug] arma path: '/drive/jogos/SteamLibrary/steamapps/common/Arma 3', workshop path: '/drive/jogos/SteamLibrary/steamapps/workshop/content/107410'
[S_API] SteamAPI_Init(): Loaded '/home/lango/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 107410
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197990460499 [API loaded no]
[2023-08-27 10:38:48.407] [trace] trying to get workshop mods
[2023-08-27 10:38:51.088] [trace] void MainWindow::on_button_start_clicked():174
[2023-08-27 10:38:51.365] [trace] Mod list: 
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1883956552
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1673456286
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/623475643
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/773131200
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/773125288
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/884966711
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2174495332
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2633537792
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/463939057
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/820924072
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2260572637
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/450814997
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/583496184
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/583544987
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2926828901
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1224892496
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/773759919
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2648308937
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2834576684
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1726494027
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1858075458
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1808238502
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1858070328
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2521192995
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/779520435
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2801060088
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2595680138
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/735566597
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/843425103
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/843593391
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/843632231
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/843577117
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1661066023
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1527410521
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/894678801
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2975574656
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2975268929
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1926513010
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/2018593688
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/workshop/content/107410/1779063631
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/common/Arma 3/vn
[2023-08-27 10:38:51.365] [trace] path: /drive/jogos/SteamLibrary/steamapps/common/Arma 3/WS
[2023-08-27 10:38:51.634] [debug] Writing config to '/drive/jogos/SteamLibrary/steamapps/common/Arma 3/../../compatdata/107410/pfx/drive_c/users/steamuser/My Documents/Arma 3/Arma3.cfg':
steamLanguage="";
language="English";
forcedAdapterId=-1;
detectedAdapterId=0;
detectedAdapterVendorId=4098;
detectedAdapterDeviceId=26591;
detectedAdapterSubSysId=0;
detectedAdapterRevision=0;
detectedAdapterBenchmark=9;
detectedCPUBenchmark=80;
detectedCPUFrequency=3700;
detectedCPUCores=12;
detectedCPUDescription="AMD Ryzen 5 5600X 6-Core Processor             ";
displayMode=0;
winX=16;
winY=32;
winWidth=1024;
winHeight=768;
winDefWidth=1024;
winDefHeight=768;
fullScreenWidth=2560;
fullScreenHeight=1440;
refresh=144;
renderWidth=2560;
renderHeight=1440;
multiSampleCount=8;
multiSampleQuality=0;
particlesQuality=2;
GPU_MaxFramesAhead=1000;
GPU_DetectedFramesAhead=2;
HDRPrecision=16;
vsync=1;
AToC=15;
cloudsQuality=4;
waterSSReflectionsQuality=0;
pipQuality=4;
dynamicLightsQuality=4;
PPAA=7;
ppSSAO=6;
ppCaustics=1;
tripleBuffering=0;
ppBloom=1;
ppRotBlur=1;
ppRadialBlur=1;
ppDOF=1;
ppSharpen=0.5;
class ModLauncherList
{
    class Mod1
    {
        dir="1883956552";
        name="16AA public mods";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1883956552";
    };
    class Mod2
    {
        dir="1673456286";
        name="3CB Factions";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1673456286";
    };
    class Mod3
    {
        dir="623475643";
        name="3den Enhanced";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\623475643";
    };
    class Mod4
    {
        dir="773131200";
        name="ACE Compat - RHS AFRF";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\773131200";
    };
    class Mod5
    {
        dir="773125288";
        name="ACE Compat - RHS USAF";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\773125288";
    };
    class Mod6
    {
        dir="884966711";
        name="ACE Compat - RHS: GREF";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\884966711";
    };
    class Mod7
    {
        dir="2174495332";
        name="ACE Compat - RHS: SAF";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2174495332";
    };
    class Mod8
    {
        dir="2633537792";
        name="ACE Compat - SOG";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2633537792";
    };
    class Mod9
    {
        dir="463939057";
        name="Advanced Combat Environment 3.15.2";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\463939057";
    };
    class Mod10
    {
        dir="820924072";
        name="BackpackOnChest";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\820924072";
    };
    class Mod11
    {
        dir="2260572637";
        name="BettIR (Development/Alpha)";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2260572637";
    };
    class Mod12
    {
        dir="450814997";
        name="Community Base Addons v3.15.8";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\450814997";
    };
    class Mod13
    {
        dir="583496184";
        name="CUP Terrains - Core 1.17.1";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\583496184";
    };
    class Mod14
    {
        dir="583544987";
        name="CUP Terrains - Maps 1.16.0";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\583544987";
    };
    class Mod15
    {
        dir="2926828901";
        name="Fallujah 2.0.";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2926828901";
    };
    class Mod16
    {
        dir="1224892496";
        name="Gruppe Adler Trenches";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1224892496";
    };
    class Mod17
    {
        dir="773759919";
        name="Iron Front in Arma 3 ACE compatibility";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\773759919";
    };
    class Mod18
    {
        dir="2648308937";
        name="Iron Front in Arma 3 All in One Second Wave";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2648308937";
    };
    class Mod19
    {
        dir="2834576684";
        name="ITN Beta";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2834576684";
    };
    class Mod20
    {
        dir="1726494027";
        name="Kujari";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1726494027";
    };
    class Mod21
    {
        dir="1858075458";
        name="LAMBS Danger.fsm 2.6.0";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1858075458";
    };
    class Mod22
    {
        dir="1808238502";
        name="LAMBS Suppression";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1808238502";
    };
    class Mod23
    {
        dir="1858070328";
        name="LAMBS_RPG";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1858070328";
    };
    class Mod24
    {
        dir="2521192995";
        name="LAMBS_RPG_RHS";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2521192995";
    };
    class Mod25
    {
        dir="779520435";
        name="Multi-play Unifroms";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\779520435";
    };
    class Mod26
    {
        dir="2801060088";
        name="Niakala";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2801060088";
    };
    class Mod27
    {
        dir="2595680138";
        name="NIArms All In One (V14 Onwards)";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2595680138";
    };
    class Mod28
    {
        dir="735566597";
        name="Project OPFOR";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\735566597";
    };
    class Mod29
    {
        dir="843425103";
        name="RHS: Armed Forces of the Russian Federation";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\843425103";
    };
    class Mod30
    {
        dir="843593391";
        name="RHS: GREF";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\843593391";
    };
    class Mod31
    {
        dir="843632231";
        name="RHS: Serbian Armed Forces";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\843632231";
    };
    class Mod32
    {
        dir="843577117";
        name="RHS: United States Forces";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\843577117";
    };
    class Mod33
    {
        dir="1661066023";
        name="RKSL Attachments Pack";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1661066023";
    };
    class Mod34
    {
        dir="1527410521";
        name="Rosche, Germany";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1527410521";
    };
    class Mod35
    {
        dir="894678801";
        name="Task Force Arrowhead Radio (BETA!!!)";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\894678801";
    };
    class Mod36
    {
        dir="2975574656";
        name="TPNVG BetterIR Compat by Moltes";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2975574656";
    };
    class Mod37
    {
        dir="2975268929";
        name="TPNVG by Moltes";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2975268929";
    };
    class Mod38
    {
        dir="1926513010";
        name="Virolahti - Valtatie 7";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1926513010";
    };
    class Mod39
    {
        dir="2018593688";
        name="Zeus Enhanced - ACE3 Compatibility";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\2018593688";
    };
    class Mod40
    {
        dir="1779063631";
        name="Zeus Enhanced 1.14.0";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\workshop\content\107410\1779063631";
    };
    class Mod41
    {
        dir="vn";
        name="$STR_A3_VN_CFGMODS_NAMESHORT";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\common\Arma 3\vn";
    };
    class Mod42
    {
        dir="WS";
        name="Arma 3 Creator DLC: Western Sahara";
        origin="GAME DIR";
        fullPath="Z:\drive\jogos\SteamLibrary\steamapps\common\Arma 3\WS";
    };
};

[2023-08-27 10:38:51.635] [trace] void ARMA3::Client::Start(const std::string&, const std::string&, bool, bool):198 arguments: ' -enableHT -exThreads=0 -hugepages -noLogs -noSplash -skipIntro -world=empty', user_environment_variables: '', launch_directly: true, disable_esync: false
[2023-08-27 10:38:51.635] [trace] void {anonymous}::direct_launch(const std::filesystem::__cxx11::path&, const std::filesystem::__cxx11::path&, const std::string&, bool, const std::string&, bool):62 arma path: '"/drive/jogos/SteamLibrary/steamapps/common/Arma 3"', executable path: '"/drive/jogos/SteamLibrary/steamapps/common/Arma 3/arma3_x64.exe"', arguments:  -enableHT -exThreads=0 -hugepages -noLogs -noSplash -skipIntro -world=empty, is_proton: true, user_environment_variables: , disable_esync: false
[2023-08-27 10:38:51.635] [info] Steam path: /home/lango/.local/share/Steam
[2023-08-27 10:38:51.635] [trace] GetCompatibilityToolForAppId:104
[2023-08-27 10:38:51.636] [critical] Direct launch failed, exception: Syntax error: VDF: Quote or bracket expected
```

**Comment by memchr** [comment]
The simple parser implemented in [VDF](https://github.com/muttleyxd/arma3-unix-launcher/blob/188ca64ffc00c151be40524ff496a7c2f91e1616/src/arma3-unix-launcher-library/vdf.cpp#L89-L97) probably won't work well, as it can legally contain unbalanced quotes or braces.
e.g.
```
"name"          "External: eDP-1 15\"|||Fullscreen-1908x1041"
```

It may also contain embedded json.

**Comment by josefius** [comment]
I'm getting this myself, I had changed Compatibility in Steam to "Proton 7.0-6" last night and it worked, however today it fails with:

[2024-03-28 18:28:28.228] [info] Steam path: /home/josefius/.steam/debian-installation
[2024-03-28 18:28:28.228] [trace] GetCompatibilityToolForAppId:104
[2024-03-28 18:28:28.228] [critical] Direct launch failed, exception: Syntax error: VDF: Quote or bracket expected

I'm running Linux Mint and I compiled from source from the git branch.
